export type Lang = "en" | "id";

export const content = {
  en: {
    nav: {
      about: "About",
      services: "Services",
      projects: "Projects",
      contact: "Contact",
    },
    hero: {
      greeting: "Hello, I'm",
      name: "Hosea Felix Sanjaya",
      role: "Data Enthusiast",
      institution: "Informatics Engineering · ITS Surabaya",
      description:
        "An Informatics Engineering student at ITS with a strong passion for problem-solving, technological innovation, and technopreneurship. I love transforming raw data into meaningful insights to build impactful solutions.",
      cta: "Explore My Work",
      ctaSecondary: "Get in Touch",
      badge: "Available for collaboration",
    },
    about: {
      label: "About",
      title: "Curious by nature, data-driven by choice.",
      p1: "I'm an Informatics Engineering student at ITS Surabaya, passionate about the sweet spot between software engineering and data.",
      p2: "From building solid backends to running algorithms like K-means clustering, my goal is always the same: write clean code and build systems that matter.",
      p3: "When I'm not studying, I serve as the Head of Event at my student association (HMTC), designing major campus tournaments and balancing team management with late-night coding sessions!",
      stats: [
        { value: "10+", label: "Technologies Used" },
        { value: "5+", label: "Active Organizations" },
        { value: "3+", label: "Leadership Roles" },
        { value: "2+", label: "Major IT Events" },
      ],
      skills: ["Next.js", "TypeScript", "Python", "Java", "PHP", "MySQL", "Docker", "Git"],
    },
    services: {
      label: "Services",
      title: "What I bring to the table.",
      subtitle: "A synthesis of software, systems, and structure.",
      items: [
        {
          icon: "Code2",
          title: "Software Engineering",
          desc: "Full-stack web development with modern frameworks — clean architecture, scalable REST APIs, and highly performant, accessible UIs.",
          tags: ["Next.js", "TypeScript", "Node.js", "Java/PHP"],
        },
        {
          icon: "Network",
          title: "Computer Networking",
          desc: "Network design, configuration, and security analysis. From structured LAN topologies to cloud infrastructure, VPNs, and SDN implementations.",
          tags: ["Cisco", "Wireshark", "Linux", "GNS3"],
        },
        {
          icon: "Database",
          title: "Database Management",
          desc: "Designing optimized relational schemas with advanced SQL normalization, alongside implementing data analysis algorithms like K-means clustering.",
          tags: ["PostgreSQL", "MySQL", "Data Structures", "Python"],
        },
        {
          icon: "Layers",
          title: "UI/UX Design",
          desc: "Human-centered design from wireframe to polished interface. Crafting experiences that guide intuitively, look exceptional, and perform flawlessly.",
          tags: ["Figma", "Design Systems", "Accessibility"],
        },
      ],
    },
    projects: {
      label: "Projects",
      title: "Selected work.",
      subtitle: "A curated set of things I've built and shipped.",
      cta: "View All on GitHub",
      items: [
        {
          title: "Wordle Solver",
          tag: "Algorithm",
          year: "2025",
          desc: "An algorithmic program designed to solve the Wordle game automatically and optimally using advanced data structures.",
          tech: ["Python", "Algorithms", "Data Structures"],
          link: "https://wordle-solver-mocha.vercel.app/",
          featured: true,
        },
        {
          title: "Artha Pamenang Company Profile",
          tag: "Web App",
          year: "2026",
          desc: "A responsive and modern corporate profile website built to establish a strong digital presence for Artha Pamenang.",
          tech: ["HTML", "CSS", "JavaScript"],
          link: "https://arthapamenangsyariah.netlify.app/",
          featured: true,
        },
        {
          title: "Expense Tracker",
          tag: "Web App",
          year: "2025",
          desc: "A web-based financial tracking application to manage daily expenses and incomes efficiently, built with Java Server Pages.",
          tech: ["Java", "JSP", "Servlets", "MySQL"],
          link: "https://github.com/abidalfrz/final-project-pemrograman-berorientasi-objek",
          featured: false,
        },
        {
          title: "Academic Information System",
          tag: "Web App",
          year: "2025",
          desc: "A comprehensive academic management system built to handle student data, lecturers, and grading effectively.",
          tech: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
          link: "https://github.com/Pascalllllll/web-programming-quiz-2",
          featured: false,
        },
      ],
    },
    contact: {
      label: "Contact",
      title: "Let's build something together.",
      subtitle:
        "Whether you have a project in mind, a question, or just want to connect — my inbox is always open.",
      namePlaceholder: "Your Name",
      emailPlaceholder: "your@email.com",
      messagePlaceholder: "Tell me about your project...",
      send: "Send Message",
      sending: "Sending...",
      success: "Message sent! I'll get back to you within 24 hours.",
      orReach: "Or reach me directly",
    },
    footer: {
      tagline: "Designed & built with care in Surabaya.",
      rights: "All rights reserved.",
    },
  },

  id: {
    nav: {
      about: "Tentang",
      services: "Layanan",
      projects: "Proyek",
      contact: "Kontak",
    },
    hero: {
      greeting: "Halo, saya",
      name: "Hosea Felix Sanjaya",
      role: "Data Enthusiast",
      institution: "Teknik Informatika · ITS Surabaya",
      description:
        "Mahasiswa Teknik Informatika ITS dengan minat besar pada pemecahan masalah, inovasi teknologi, dan technopreneurship. Saya mengubah data menjadi wawasan bermakna untuk membangun solusi yang berdampak.",
      cta: "Jelajahi Karya Saya",
      ctaSecondary: "Hubungi Saya",
      badge: "Tersedia untuk kolaborasi",
    },
    about: {
      label: "Tentang",
      title: "Secara alami penasaran, memilih digerakkan oleh data.",
      p1: "Saya mahasiswa Teknik Informatika di ITS Surabaya. Saya sangat menyukai titik temu antara rekayasa perangkat lunak dan data.",
      p2: "Mulai dari membangun backend yang solid hingga menjalankan algoritma seperti K-means clustering, tujuan saya selalu sama: menulis kode yang bersih dan membangun sistem yang bermanfaat.",
      p3: "Di luar jam kuliah, saya aktif sebagai Kepala Biro Event di himpunan mahasiswa (HMTC). Saya merancang turnamen kampus berskala besar sambil menyeimbangkan waktu antara manajemen tim dan keseruan coding di larut malam!",
      stats: [
        { value: "10+", label: "Teknologi Dikuasai" },
        { value: "5+", label: "Organisasi Aktif" },
        { value: "3+", label: "Posisi Leadership" },
        { value: "2+", label: "Event IT Besar" },
      ],
      skills: ["Next.js", "TypeScript", "Python", "Java", "PHP", "MySQL", "Docker", "Git"],
    },
    services: {
      label: "Layanan",
      title: "Yang saya tawarkan.",
      subtitle: "Sintesis perangkat lunak, sistem, dan struktur.",
      items: [
        {
          icon: "Code2",
          title: "Rekayasa Perangkat Lunak",
          desc: "Pengembangan web full-stack dengan framework modern — arsitektur bersih, API REST yang skalabel, dan UI yang berkinerja tinggi dan aksesibel.",
          tags: ["Next.js", "TypeScript", "Node.js", "Java/PHP"],
        },
        {
          icon: "Network",
          title: "Jaringan Komputer",
          desc: "Desain, konfigurasi, dan analisis keamanan jaringan. Dari topologi LAN terstruktur hingga infrastruktur cloud, VPN, dan implementasi SDN.",
          tags: ["Cisco", "Wireshark", "Linux", "GNS3"],
        },
        {
          icon: "Database",
          title: "Manajemen Basis Data",
          desc: "Merancang skema relasional yang dioptimalkan melalui normalisasi SQL, serta menerapkan algoritma analisis data seperti K-means clustering.",
          tags: ["PostgreSQL", "MySQL", "Struktur Data", "Python"],
        },
        {
          icon: "Layers",
          title: "Desain UI/UX",
          desc: "Desain berpusat manusia dari wireframe hingga antarmuka yang dipoles. Menciptakan pengalaman yang memandu secara intuitif dan tampil luar biasa.",
          tags: ["Figma", "Design Systems", "Accessibility"],
        },
      ],
    },
    projects: {
      label: "Proyek",
      title: "Karya pilihan.",
      subtitle: "Kumpulan hal-hal yang telah saya bangun dan rilis.",
      cta: "Lihat Semua di GitHub",
      items: [
        {
          title: "Wordle Solver",
          tag: "Algoritma",
          year: "2025",
          desc: "Program algoritma yang dirancang untuk memecahkan permainan Wordle secara otomatis dan optimal menggunakan struktur data tingkat lanjut.",
          tech: ["Python", "Algorithms", "Data Structures"],
          link: "https://wordle-solver-mocha.vercel.app/",
          featured: true,
        },
        {
          title: "Artha Pamenang Company Profile",
          tag: "Aplikasi Web",
          year: "2026",
          desc: "Website profil perusahaan yang responsif dan modern untuk memperkuat presensi digital Artha Pamenang.",
          tech: ["HTML", "CSS", "JavaScript"],
          link: "https://arthapamenangsyariah.netlify.app/",
          featured: true,
        },
        {
          title: "Expense Tracker",
          tag: "Aplikasi Web",
          year: "2025",
          desc: "Aplikasi pencatat keuangan berbasis web untuk mengelola pemasukan dan pengeluaran harian secara efisien, dibangun dengan JSP.",
          tech: ["Java", "JSP", "Servlets", "MySQL"],
          link: "https://github.com/abidalfrz/final-project-pemrograman-berorientasi-objek",
          featured: false,
        },
        {
          title: "Sistem Akademik",
          tag: "Aplikasi Web",
          year: "2025",
          desc: "Sistem informasi akademik komprehensif untuk mengelola data mahasiswa, dosen, dan rekapitulasi nilai dengan efektif.",
          tech: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
          link: "https://github.com/Pascalllllll/web-programming-quiz-2",
          featured: false,
        },
      ],
    },
    contact: {
      label: "Kontak",
      title: "Mari bangun sesuatu bersama.",
      subtitle:
        "Apakah Anda memiliki proyek, pertanyaan, atau sekadar ingin terhubung — kotak masuk saya selalu terbuka.",
      namePlaceholder: "Nama Anda",
      emailPlaceholder: "email@anda.com",
      messagePlaceholder: "Ceritakan tentang proyek Anda...",
      send: "Kirim Pesan",
      sending: "Mengirim...",
      success: "Pesan terkirim! Saya akan membalas dalam 24 jam.",
      orReach: "Atau hubungi langsung",
    },
    footer: {
      tagline: "Dirancang & dibangun dengan penuh perhatian di Surabaya.",
      rights: "Hak cipta dilindungi.",
    },
  },
} as const;