export const content = {
  nav: {
    about: "About",
    experience: "Experience",
    projects: "Projects",
    contact: "Contact",
    skip: "Skip to content",
    home: "Back to top",
    playMusic: "Play Misery by Pupsies",
    pauseMusic: "Pause music",
    menu: "Menu",
    close: "Close",
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
  },
  hero: {
    name: "Hosea Felix Sanjaya",
    typing: ["Part-time gamer.", "I use Debian :v", "Unemployee.."],
    role: "Informatics Engineering student at ITS Surabaya.",
    description:
      "I turn raw data into something people can act on, then spend the evening theming my desktop. [[I use Debian, btw.]]",
    cta: "See my projects",
    ctaSecondary: "Send me a message",
  },
  about: {
    label: "About",
    title: "Data in the day, dotfiles at night",
    p1: "I'm an Informatics Engineering student at ITS Surabaya. The work I enjoy most starts with a messy dataset and ends with a table or chart someone can make a decision from.",
    p2: "Cleaning data and ricing a Linux desktop scratch the same itch for me: I keep adjusting small things until nothing looks off. The difference is that nobody asks to see my fish config.",
    p3: "Outside class I'm [[Head of Event at HMTC]], my student association. I plan campus tournaments and manage the team, then catch up on code late at night.",
    facts: [
      { label: "Studying", value: "Informatics Engineering, ITS" },
      { label: "Role", value: "Head of Event, HMTC" },
      { label: "Based in", value: "Surabaya, Indonesia" },
      { label: "GPA", value: "3.77", note: "(4.00 on last semester :v)" },
    ],
    skillsLabel: "Technologies",
    // Programming and web first, then data, then Linux ricing.
    skills: ["Python", "Java", "TypeScript", "React", "Next.js", "Tailwind CSS", "Git", "Docker", "pandas", "scikit-learn", "PostgreSQL", "MySQL", "Debian", "GNOME"],
    cv: "Download CV (PDF)",
    photoAlt: "Portrait of Hosea Felix Sanjaya",
  },
  focus: {
    label: "Focus",
    title: "What I work on",
    items: [
      {
        title: "Data analysis",
        desc: "Cleaning raw data in Python and grouping or charting it until the pattern is clear, for example with K-means clustering.",
        tags: ["Python", "pandas", "scikit-learn", "Jupyter"],
      },
      {
        title: "Databases",
        desc: "Relational schemas normalised in SQL, and the queries that pull data out of them for analysis.",
        tags: ["PostgreSQL", "MySQL", "SQL"],
      },
      {
        title: "Linux ricing",
        desc: "Debian with GNOME on Wayland, themed down to the terminal: fish with a Starship prompt, fastfetch for the screenshots, and Spotify skinned with Spicetify.",
        tags: ["Debian", "GNOME", "fish", "Starship", "fastfetch", "Spicetify"],
      },
      {
        title: "UI/UX design",
        desc: "From wireframe to finished interface in Figma, with accessibility checked along the way.",
        tags: ["Figma", "Design systems", "Accessibility"],
      },
    ],
  },
  projects: {
    label: "Projects",
    title: "Selected work",
    cta: "All repositories on GitHub",
    live: "Live site",
    code: "Source on GitHub",
    newTab: "opens in a new tab",
    viewMore: "View more",
    showLess: "Show less",
    moreMessage: "Trust me, I have more…",
    items: [
      {
        title: "Unfinalized",
        tag: "Game",
        year: "2026",
        desc: "A parkour game where every stone is a live Ethereum transaction. Reach the newest block before the rising floor catches you.",
        tech: ["JavaScript", "Three.js", "viem", "Ethereum"],
        link: "https://unfinalized.vercel.app/",
        preview: "/project/unfinalized.webp",
        kind: "live",
        featured: false,
      },
      {
        title: "Wordle Solver",
        tag: "Algorithm",
        year: "2025",
        desc: "Solves Wordle puzzles in the browser, choosing each next guess with an algorithm.",
        tech: ["Python", "Algorithms", "Data structures"],
        link: "https://wordle-solver-mocha.vercel.app/",
        preview: "/project/wordle-solver.webp",
        kind: "live",
        featured: true,
      },
      {
        title: "Pluck",
        tag: "Tool",
        year: "2026",
        desc: "Erases photo backgrounds in the browser, with a brush or by detecting the subject. Nothing gets uploaded.",
        tech: ["JavaScript", "Canvas", "ONNX Runtime"],
        link: "https://pascalllllll.github.io/Background-eraser-desktop/",
        preview: "/project/pluck.webp",
        kind: "live",
        featured: false,
      },
      {
        title: "Antislop Paraphrase",
        tag: "Tool",
        year: "2026",
        desc: "Paste text that sounds like a chatbot wrote it. You get it back with the AI tells crossed out.",
        tech: ["JavaScript", "Web Workers", "HTML", "CSS"],
        link: "https://antislop-paraphrase.vercel.app/",
        preview: "/project/antislop-paraphrase.webp",
        kind: "live",
        featured: false,
      },
      {
        title: "Call-me",
        tag: "Web",
        year: "2026",
        desc: "Self-hosted group calls and chat. Channels like Discord, one-click meetings like Zoom, and calls that never time out.",
        tech: ["Node.js", "Express", "WebRTC", "WebSocket", "SQLite"],
        link: "https://github.com/Pascalllllll/Call-me",
        preview: "/project/call-me.webp",
        kind: "code",
        featured: false,
      },
      {
        title: "Expense Tracker",
        tag: "Web",
        year: "2025",
        desc: "A web app for logging daily income and expenses, built on Java Server Pages.",
        tech: ["Java", "JSP", "Servlets", "MySQL"],
        link: "https://github.com/abidalfrz/final-project-pemrograman-berorientasi-objek",
        preview: "/project/expense-tracker.webp",
        kind: "code",
        featured: false,
      },
      {
        title: "PustaRasa",
        tag: "Database",
        year: "2026",
        desc: "One MySQL database for a library's book loans, canteen orders, and visitor log.",
        tech: ["MySQL", "Express", "React", "Tailwind CSS"],
        link: "https://github.com/Pascalllllll/FP-MBD-Pustarasa",
        preview: "/project/pustarasa.webp",
        kind: "code",
        featured: false,
      },
      {
        title: "Artha Pamenang company profile",
        tag: "Web",
        year: "2026",
        desc: "Company profile site for Artha Pamenang that reads well on phones and desktops.",
        tech: ["HTML", "CSS", "JavaScript"],
        link: "https://arthapamenangsyariah.netlify.app/",
        preview: "/project/artha-pamenang.webp",
        kind: "live",
        featured: true,
      },
    ],
    initialCount: 4,
  },
  experience: {
    label: "Experience",
    title: "Where I've been involved",
    present: "Present",
    roles: "roles",
    yr: "yr",
    yrs: "yrs",
    mo: "mo",
    mos: "mos",
  },
  contact: {
    label: "Contact",
    title: "Write to me",
    subtitle:
      "A project, an event, a question about something on this page. The form goes straight to my inbox.",
    nameLabel: "Name",
    emailLabel: "Email",
    messageLabel: "Message",
    namePlaceholder: "Your name",
    emailPlaceholder: "you@example.com",
    messagePlaceholder: "What would you like to talk about?",
    send: "Send message",
    sending: "Sending…",
    success: "Message sent. I'll reply to the email address you gave.",
    sendAnother: "Send another message",
    errorTitle: "Your message didn't send.",
    errorNetwork: "The form couldn't reach the server. Check your connection and try again, or email me directly at",
    errorBusy: "Several messages were sent in a short time. Wait a few minutes and try again, or email me directly at",
    errorServer: "The form isn't working on my side right now, so your message wasn't sent. Please email me directly at",
    retry: "Back to the form",
    orReach: "Or reach me directly",
    errName: "Please enter your name.",
    errEmailEmpty: "Please enter your email address.",
    errEmailInvalid: "That email address doesn't look complete, for example name@example.com.",
    errMessage: "Please write a message.",
  },
} as const;
