export type Lang = "en" | "id";

export const content = {
  en: {
    nav: {
      about: "About",
      projects: "Projects",
      contact: "Contact",
      skip: "Skip to content",
      home: "Back to top",
      playMusic: "Play Misery by Pupsies",
      pauseMusic: "Pause music",
      menu: "Menu",
      close: "Close",
      toLight: "Switch to light theme",
      toDark: "Switch to dark theme",
      toggleLang: "Baca dalam Bahasa Indonesia",
    },
    hero: {
      name: "Hosea Felix Sanjaya",
      role: "Informatics Engineering student at ITS Surabaya.",
      description:
        "I turn raw data into something people can act on, then spend the evening theming my desktop. I use Debian, btw.",
      cta: "See my projects",
      ctaSecondary: "Send me a message",
    },
    about: {
      label: "About",
      title: "Data in the day, dotfiles at night",
      p1: "I'm an Informatics Engineering student at ITS Surabaya. The work I enjoy most starts with a messy dataset and ends with a table or chart someone can make a decision from.",
      p2: "Cleaning data and ricing a Linux desktop scratch the same itch for me: I keep adjusting small things until nothing looks off. The difference is that nobody asks to see my fish config.",
      p3: "Outside class I'm Head of Event at HMTC, my student association. I plan campus tournaments and manage the team, then catch up on code late at night.",
      facts: [
        { label: "Studying", value: "Informatics Engineering, ITS" },
        { label: "Role", value: "Head of Event, HMTC" },
        { label: "Based in", value: "Surabaya, Indonesia" },
        { label: "GPA", value: "3.77" },
      ],
      skillsLabel: "Technologies",
      skills: ["Python", "pandas", "PostgreSQL", "MySQL", "TypeScript", "Next.js", "Git", "Debian", "GNOME", "fish", "Starship"],
      cv: "Download CV (PDF)",
      photoAlt: "Portrait of Hosea Felix Sanjaya",
    },
    focus: {
      label: "Focus",
      title: "What I work on",
      items: [
        {
          title: "Data analysis",
          desc: "Cleaning raw data in Python and grouping or charting it until the pattern is clear, for example with K-means clustering.",
          tags: ["Python", "pandas", "scikit-learn", "Jupyter"],
        },
        {
          title: "Databases",
          desc: "Relational schemas normalised in SQL, and the queries that pull data out of them for analysis.",
          tags: ["PostgreSQL", "MySQL", "SQL"],
        },
        {
          title: "Linux ricing",
          desc: "Debian with GNOME on Wayland, themed down to the terminal: fish with a Starship prompt, fastfetch for the screenshots, and Spotify skinned with Spicetify.",
          tags: ["Debian", "GNOME", "fish", "Starship", "fastfetch", "Spicetify"],
        },
        {
          title: "UI/UX design",
          desc: "From wireframe to finished interface in Figma, with accessibility checked along the way.",
          tags: ["Figma", "Design systems", "Accessibility"],
        },
      ],
    },
    projects: {
      label: "Projects",
      title: "Selected work",
      cta: "All repositories on GitHub",
      live: "Live site",
      code: "Source on GitHub",
      newTab: "opens in a new tab",
      items: [
        {
          title: "Wordle Solver",
          tag: "Algorithm",
          year: "2025",
          desc: "Solves Wordle games automatically, picking each next guess with an algorithm. Runs in the browser.",
          tech: ["Python", "Algorithms", "Data structures"],
          link: "https://wordle-solver-mocha.vercel.app/",
          kind: "live",
          featured: true,
        },
        {
          title: "Artha Pamenang company profile",
          tag: "Web",
          year: "2026",
          desc: "Company profile website for Artha Pamenang, laid out to work from phone to desktop.",
          tech: ["HTML", "CSS", "JavaScript"],
          link: "https://arthapamenangsyariah.netlify.app/",
          kind: "live",
          featured: true,
        },
        {
          title: "Expense Tracker",
          tag: "Web",
          year: "2025",
          desc: "Records daily income and expenses. Built with Java Server Pages and MySQL.",
          tech: ["Java", "JSP", "Servlets", "MySQL"],
          link: "https://github.com/abidalfrz/final-project-pemrograman-berorientasi-objek",
          kind: "code",
          featured: false,
        },
        {
          title: "Academic Information System",
          tag: "Web",
          year: "2025",
          desc: "Manages student records, lecturers, and grades.",
          tech: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
          link: "https://github.com/Pascalllllll/web-programming-quiz-2",
          kind: "code",
          featured: false,
        },
      ],
    },
    contact: {
      label: "Contact",
      title: "Write to me",
      subtitle:
        "A project, an event, a question about something on this page. The form goes straight to my inbox.",
      nameLabel: "Name",
      emailLabel: "Email",
      messageLabel: "Message",
      namePlaceholder: "Your name",
      emailPlaceholder: "you@example.com",
      messagePlaceholder: "What would you like to talk about?",
      send: "Send message",
      sending: "Sending...",
      success: "Message sent. I'll reply to the email address you gave.",
      sendAnother: "Send another message",
      errorTitle: "Your message didn't send.",
      errorBody: "Check your connection and try again, or email me directly at",
      retry: "Back to the form",
      orReach: "Or reach me directly",
      errName: "Please enter your name.",
      errEmailEmpty: "Please enter your email address.",
      errEmailInvalid: "That email address doesn't look complete, for example name@example.com.",
      errMessage: "Please write a message.",
    },
    footer: {
      rights: "All rights reserved.",
    },
  },

  id: {
    nav: {
      about: "Tentang",
      projects: "Proyek",
      contact: "Kontak",
      skip: "Langsung ke konten",
      home: "Kembali ke atas",
      playMusic: "Putar Misery oleh Pupsies",
      pauseMusic: "Jeda musik",
      menu: "Menu",
      close: "Tutup",
      toLight: "Ganti ke tema terang",
      toDark: "Ganti ke tema gelap",
      toggleLang: "Read in English",
    },
    hero: {
      name: "Hosea Felix Sanjaya",
      role: "Mahasiswa Teknik Informatika di ITS Surabaya.",
      description:
        "Saya mengolah data mentah menjadi sesuatu yang bisa dipakai untuk mengambil keputusan, lalu menghabiskan malam mengutak-atik tampilan desktop. I use Debian, btw.",
      cta: "Lihat proyek saya",
      ctaSecondary: "Kirim pesan",
    },
    about: {
      label: "Tentang",
      title: "Siang olah data, malam oprek dotfiles",
      p1: "Saya mahasiswa Teknik Informatika di ITS Surabaya. Pekerjaan yang paling saya nikmati dimulai dari dataset yang berantakan dan berakhir jadi tabel atau grafik yang bisa dipakai orang untuk mengambil keputusan.",
      p2: "Membersihkan data dan ricing desktop Linux ternyata memuaskan rasa gatal yang sama: saya terus membetulkan hal kecil sampai tidak ada yang terlihat janggal. Bedanya, tidak ada yang minta lihat config fish saya.",
      p3: "Di luar kuliah, saya Kepala Biro Event di HMTC, himpunan mahasiswa saya. Saya merancang turnamen kampus dan mengelola tim, lalu lanjut ngoding sampai larut malam.",
      facts: [
        { label: "Kuliah", value: "Teknik Informatika, ITS" },
        { label: "Peran", value: "Kepala Biro Event, HMTC" },
        { label: "Domisili", value: "Surabaya, Indonesia" },
        { label: "IPK", value: "3.77" },
      ],
      skillsLabel: "Teknologi",
      skills: ["Python", "pandas", "PostgreSQL", "MySQL", "TypeScript", "Next.js", "Git", "Debian", "GNOME", "fish", "Starship"],
      cv: "Unduh CV (PDF)",
      photoAlt: "Foto Hosea Felix Sanjaya",
    },
    focus: {
      label: "Bidang",
      title: "Yang saya kerjakan",
      items: [
        {
          title: "Analisis data",
          desc: "Membersihkan data mentah dengan Python, lalu mengelompokkan atau memvisualisasikannya sampai polanya terlihat, misalnya dengan K-means clustering.",
          tags: ["Python", "pandas", "scikit-learn", "Jupyter"],
        },
        {
          title: "Basis data",
          desc: "Skema relasional yang dinormalisasi dengan SQL, dan query untuk menarik datanya ke tahap analisis.",
          tags: ["PostgreSQL", "MySQL", "SQL"],
        },
        {
          title: "Ricing Linux",
          desc: "Debian dengan GNOME di Wayland, dirapikan sampai ke terminal: fish dengan prompt Starship, fastfetch untuk tangkapan layar, dan Spotify yang dikustom lewat Spicetify.",
          tags: ["Debian", "GNOME", "fish", "Starship", "fastfetch", "Spicetify"],
        },
        {
          title: "Desain UI/UX",
          desc: "Dari wireframe hingga antarmuka jadi di Figma, dengan aksesibilitas diperiksa di sepanjang prosesnya.",
          tags: ["Figma", "Design systems", "Aksesibilitas"],
        },
      ],
    },
    projects: {
      label: "Proyek",
      title: "Karya pilihan",
      cta: "Semua repositori di GitHub",
      live: "Situs langsung",
      code: "Kode di GitHub",
      newTab: "terbuka di tab baru",
      items: [
        {
          title: "Wordle Solver",
          tag: "Algoritma",
          year: "2025",
          desc: "Menyelesaikan permainan Wordle secara otomatis, memilih tebakan berikutnya dengan algoritma. Bisa dicoba di browser.",
          tech: ["Python", "Algoritma", "Struktur data"],
          link: "https://wordle-solver-mocha.vercel.app/",
          kind: "live",
          featured: true,
        },
        {
          title: "Profil perusahaan Artha Pamenang",
          tag: "Web",
          year: "2026",
          desc: "Website profil perusahaan untuk Artha Pamenang, tampil baik dari ponsel hingga desktop.",
          tech: ["HTML", "CSS", "JavaScript"],
          link: "https://arthapamenangsyariah.netlify.app/",
          kind: "live",
          featured: true,
        },
        {
          title: "Expense Tracker",
          tag: "Web",
          year: "2025",
          desc: "Mencatat pemasukan dan pengeluaran harian. Dibangun dengan Java Server Pages dan MySQL.",
          tech: ["Java", "JSP", "Servlets", "MySQL"],
          link: "https://github.com/abidalfrz/final-project-pemrograman-berorientasi-objek",
          kind: "code",
          featured: false,
        },
        {
          title: "Sistem Informasi Akademik",
          tag: "Web",
          year: "2025",
          desc: "Mengelola data mahasiswa, dosen, dan nilai.",
          tech: ["PHP", "MySQL", "Bootstrap", "JavaScript"],
          link: "https://github.com/Pascalllllll/web-programming-quiz-2",
          kind: "code",
          featured: false,
        },
      ],
    },
    contact: {
      label: "Kontak",
      title: "Kirim pesan",
      subtitle:
        "Soal proyek, acara, atau pertanyaan tentang isi halaman ini. Formulir ini langsung masuk ke kotak masuk saya.",
      nameLabel: "Nama",
      emailLabel: "Email",
      messageLabel: "Pesan",
      namePlaceholder: "Nama Anda",
      emailPlaceholder: "anda@contoh.com",
      messagePlaceholder: "Apa yang ingin Anda bicarakan?",
      send: "Kirim pesan",
      sending: "Mengirim...",
      success: "Pesan terkirim. Saya akan membalas ke alamat email yang Anda isi.",
      sendAnother: "Kirim pesan lain",
      errorTitle: "Pesan Anda gagal terkirim.",
      errorBody: "Periksa koneksi Anda dan coba lagi, atau kirim email langsung ke",
      retry: "Kembali ke formulir",
      orReach: "Atau hubungi langsung",
      errName: "Mohon isi nama Anda.",
      errEmailEmpty: "Mohon isi alamat email Anda.",
      errEmailInvalid: "Alamat email belum lengkap, contohnya nama@contoh.com.",
      errMessage: "Mohon tulis pesan Anda.",
    },
    footer: {
      rights: "Hak cipta dilindungi.",
    },
  },
} as const;
